### ISSUE TITLE
ImportError: cannot import name HttpError

### ISSUE THREAD

**Issue by alexstrat** [intercom/python-intercom#179]
```py
from intercom.client import Client
intercom = Client(personal_access_token=INTERCOM_TOKEN)
intercom.users.list()
```

ends up with:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/intercom/client.py", line 70, in users
    from intercom.service import user
  File "/usr/local/lib/python2.7/site-packages/intercom/service/user.py", line 4, in <module>
    from intercom.api_operations.all import All
  File "/usr/local/lib/python2.7/site-packages/intercom/api_operations/all.py", line 5, in <module>
    from intercom.collection_proxy import CollectionProxy
  File "/usr/local/lib/python2.7/site-packages/intercom/collection_proxy.py", line 4, in <module>
    from intercom import HttpError
ImportError: cannot import name HttpError
```

with `python-intercom==3.1.0`

Any idea?

**Comment by alexstrat** [comment]
Here is a way to workaround that:

```py
# work around https://github.com/intercom/python-intercom/issues/179
from intercom.errors import HttpError 
import intercom
intercom.HttpError = HttpError
from intercom.client import Client
intercom = Client(personal_access_token=INTERCOM_TOKEN)
intercom.users.list()
```

**Comment by tanasegabriel** [comment]
Hey @alexstrat 👋Thanks for flagging this! I'm unable to reproduce it though with Python 2.7.14:

```bash
gabriel@ubuntu-server:~$ pip show python-intercom | grep 'Version'
Version: 3.1.0
gabriel@ubuntu-server:~$ python
Python 2.7.14 (default, Sep 23 2017, 22:06:14)
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from intercom.client import Client
>>> intercom = Client(personal_access_token=[FILTERED])
>>> intercom.users.list()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'User' object has no attribute 'list'
```

Or with Python 3.6.3:

```bash
gabriel@ubuntu-server:~$ pip3 show python-intercom | grep 'Version'
Version: 3.1.0
gabriel@ubuntu-server:~$ python3
Python 3.6.3 (default, Oct  3 2017, 21:45:48)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from intercom.client import Client
>>> intercom = Client(personal_access_token=[FILTERED])
>>> intercom.users.list()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'User' object has no attribute 'list'
```

I'm seeing the correct error that indicates that `list` is not supported by the `User` method. It looks like you see some errors related to broken imports in various files, but that shouldn't be the case.

Are you using the `python-intercom` module from PyPI, or did you clone this repo and imported it locally?

**Comment by alexstrat** [comment]
@tanasegabriel

It was with Python 3.5.1 and `python-intercom` installed via PyPi.

But looks like I can't re-reproduce now.. That's weird 🤔 

I'll just close the issue and re-open with more details if I stumble on it again.

**Comment by kccheung** [comment]
I am having similar problem with 3.1.0 and python version 3.5.3 and here is my call stack:

```
ERROR ( 2018-03-14 01:37:03,645 ) - django.request -> Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "/Users/david/.pyenv/versions/powerarena-core-3.5.3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/david/.pyenv/versions/powerarena-core-3.5.3/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/david/.pyenv/versions/powerarena-core-3.5.3/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/david/.pyenv/versions/powerarena-core-3.5.3/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/david/.pyenv/versions/powerarena-core-3.5.3/lib/python3.5/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/david/.pyenv/versions/powerarena-core-3.5.3/lib/python3.5/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/Users/david/.pyenv/versions/powerarena-core-3.5.3/lib/python3.5/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/david/.pyenv/versions/powerarena-core-3.5.3/lib/python3.5/site-packages/registration/views.py", line 53, in dispatch
    return super(RegistrationView, self).dispatch(request, *args, **kwargs)
  File "/Users/david/.pyenv/versions/powerarena-core-3.5.3/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/david/.pyenv/versions/powerarena-core-3.5.3/lib/python3.5/site-packages/django/views/generic/edit.py", line 183, in post
    return self.form_valid(form)
  File "/Users/david/.pyenv/versions/powerarena-core-3.5.3/lib/python3.5/site-packages/registration/views.py", line 56, in form_valid
    new_user = self.register(form)
  File "/Users/david/app/powerarena-core/powerarena_registration/views.py", line 72, in register
    intercom_user = get_or_create_intercom_user(user=new_user, how_did_you_learn=how_did_you_learn)
  File "/Users/david/app/powerarena-core/powerarena_core/utils/intercom_utils.py", line 50, in get_or_create_intercom_user
    intercom_user = intercom_client.users.find(**kwargs)
  File "/Users/david/.pyenv/versions/powerarena-core-3.5.3/lib/python3.5/site-packages/intercom/client.py", line 70, in users
    from intercom.service import user
  File "/Users/david/.pyenv/versions/powerarena-core-3.5.3/lib/python3.5/site-packages/intercom/service/user.py", line 4, in <module>
    from intercom.api_operations.all import All
  File "/Users/david/.pyenv/versions/powerarena-core-3.5.3/lib/python3.5/site-packages/intercom/api_operations/all.py", line 5, in <module>
    from intercom.collection_proxy import CollectionProxy
  File "/Users/david/.pyenv/versions/powerarena-core-3.5.3/lib/python3.5/site-packages/intercom/collection_proxy.py", line 4, in <module>
    from intercom import HttpError
```
